services:
  keeper-commander-kdbx-exporter:
    image: ghcr.io/allit-ag/keeper-commander-kdbx-exporter:latest
    volumes:
      - /mnt/keeper-commander-kdbx-exporter/export:/mnt/keeper-commander-kdbx-exporter/export
      - /mnt/keeper-commander-kdbx-exporter/secret:/mnt/keeper-commander-kdbx-exporter/secret
